name: pure
channels:
  - defaults
dependencies:
  - ipykernel
  - python=3.9
  - pandas
  - openai
  - python-dotenv
  - pytorch
  - pytorch-cuda=12.1
  - conda-forge::transformers
  - datasets
  - wandb
  - scikit-learn
  - tqdm
  - ipywidgets
